workflows

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,194 +1,194 @@
-name: release
+# name: release
 
-on:
-    push:
-        branches: # on push to these branches
-            - main
-            - build/*
-    workflow_dispatch:
+# on:
+#     push:
+#         branches: # on push to these branches
+#             - main
+#             - build/*
+#     workflow_dispatch:
 
-concurrency:
-    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
-    cancel-in-progress: false # queue the new runs until previous have finished. This avoids version bumps overlapping with each other
+# concurrency:
+#     group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+#     cancel-in-progress: false # queue the new runs until previous have finished. This avoids version bumps overlapping with each other
 
-defaults:
-    run:
-        shell: bash
+# defaults:
+#     run:
+#         shell: bash
 
-jobs:
-    release:
-        name: release
-        runs-on: ubuntu-latest
-        steps:
-            - name: Print contexts
-              uses: prosopo/captcha/.github/actions/print_contexts@gha
-              with:
-                    INPUTS_CONTEXT: ${{ toJson(inputs) }}
-                    NEEDS_CONTEXT: ${{ toJson(needs) }}
-                    VARS_CONTEXT: ${{ toJson(vars) }}
-                    SECRETS_CONTEXT: ${{ toJson(secrets) }}
+# jobs:
+#     release:
+#         name: release
+#         runs-on: ubuntu-latest
+#         steps:
+#             - name: Print contexts
+#               uses: prosopo/captcha/.github/actions/print_contexts@gha
+#               with:
+#                     INPUTS_CONTEXT: ${{ toJson(inputs) }}
+#                     NEEDS_CONTEXT: ${{ toJson(needs) }}
+#                     VARS_CONTEXT: ${{ toJson(vars) }}
+#                     SECRETS_CONTEXT: ${{ toJson(secrets) }}
 
-            - name: Get token for gh app token
-              id: app_token
-              uses: peter-murray/workflow-application-token-action@v3
-              with:
-                application_id: ${{ vars.PROSOPONATOR_APP_ID }}
-                application_private_key: ${{ secrets.PROSOPONATOR_APP_PRIVATE_KEY }}
+#             - name: Get token for gh app token
+#               id: app_token
+#               uses: peter-murray/workflow-application-token-action@v3
+#               with:
+#                 application_id: ${{ vars.PROSOPONATOR_APP_ID }}
+#                 application_private_key: ${{ secrets.PROSOPONATOR_APP_PRIVATE_KEY }}
 
-            - uses: actions/checkout@v4
-              with:
-                  submodules: 'recursive'
-                  token: ${{ steps.app_token.outputs.token }}
-                  fetch-depth: 0 # fetch all history
+#             - uses: actions/checkout@v4
+#               with:
+#                   submodules: 'recursive'
+#                   token: ${{ steps.app_token.outputs.token }}
+#                   fetch-depth: 0 # fetch all history
 
-            - name: setup npm registry
-              run: |
-                set -x
-                echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
-                echo "//npm.pkg.github.com/:_authToken=${{ secrets.PROSOPONATOR_PAT }}" >> ~/.npmrc
+#             - name: setup npm registry
+#               run: |
+#                 set -x
+#                 echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
+#                 echo "//npm.pkg.github.com/:_authToken=${{ secrets.PROSOPONATOR_PAT }}" >> ~/.npmrc
 
-            - name: authenticate npm registry
-              run: |
-                set -x
-                npm whoami --registry https://registry.npmjs.org/
+#             - name: authenticate npm registry
+#               run: |
+#                 set -x
+#                 npm whoami --registry https://registry.npmjs.org/
 
-            - name: authenticate gh registry
-              run: |
-                set -x
-                npm whoami --registry https://npm.pkg.github.com/
+#             - name: authenticate gh registry
+#               run: |
+#                 set -x
+#                 npm whoami --registry https://npm.pkg.github.com/
 
-            - name: vars to env
-              run: |
-                VARS_JSON='${{ toJson(vars) }}'
-                KEYS=$(echo "$VARS_JSON" | jq -r 'keys[]')
-                for key in $KEYS; do
-                  value=$(echo "$VARS_JSON" | jq -r --arg key "$key" '.[$key]')
-                  echo "$key: $value"
-                  echo "$key=$value" >> $GITHUB_ENV
-                done
+#             - name: vars to env
+#               run: |
+#                 VARS_JSON='${{ toJson(vars) }}'
+#                 KEYS=$(echo "$VARS_JSON" | jq -r 'keys[]')
+#                 for key in $KEYS; do
+#                   value=$(echo "$VARS_JSON" | jq -r --arg key "$key" '.[$key]')
+#                   echo "$key: $value"
+#                   echo "$key=$value" >> $GITHUB_ENV
+#                 done
 
-            - name: git config
-              run: |
-                set -x
-                git config user.name "prosoponator[bot]"
-                git config user.email "dev@prosopo.io"
+#             - name: git config
+#               run: |
+#                 set -x
+#                 git config user.name "prosoponator[bot]"
+#                 git config user.email "dev@prosopo.io"
 
-            - run: npm ci
+#             - run: npm ci
 
-            - name: Apply version bumps
-              env: 
-                GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
-              run: |
-                # if there are changesets, apply them
-                if find .nx/version-plans -type f -print -quit | grep -q .; then
-                  echo "Found changeset files"
-                  npx nx release --first-release
-                  git status
-                  git push
-                  git push --tags
-                else
-                  echo "No changeset files found"
-                fi
+#             - name: Apply version bumps
+#               env: 
+#                 GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
+#               run: |
+#                 # if there are changesets, apply them
+#                 if find .nx/version-plans -type f -print -quit | grep -q .; then
+#                   echo "Found changeset files"
+#                   npx nx release --first-release
+#                   git status
+#                   git push
+#                   git push --tags
+#                 else
+#                   echo "No changeset files found"
+#                 fi
 
-            - name: affected
-              run: |
-                affected=$(npx nx show projects --json --affected --base=${{ github.sha }} --head=HEAD)
-                echo "affected: $affected"
-                echo "affected=$affected" >> $GITHUB_ENV
+#             - name: affected
+#               run: |
+#                 affected=$(npx nx show projects --json --affected --base=${{ github.sha }} --head=HEAD)
+#                 echo "affected: $affected"
+#                 echo "affected=$affected" >> $GITHUB_ENV
                 
-            - name: publish to npm
-              id: publish_npm
-              run: |
-                # for each affected package
-                output="[]"
-                for pkg in $(echo $affected | jq -r '.[]'); do
-                    echo "Publishing $pkg"
-                    set +e
-                    npm publish -w "$pkg" --access public --registry https://registry.npmjs.org
-                    result=$?
-                    set -e
-                    if [ $result -eq 0 ]; then
-                      output=$(echo "$output" | jq -c ". += [{\"package\": \"$pkg\", \"ok\": true}]")
-                    else
-                      output=$(echo "$output" | jq -c ". += [{\"package\": \"$pkg\", \"ok\": false}]")
-                    fi
-                done
+#             - name: publish to npm
+#               id: publish_npm
+#               run: |
+#                 # for each affected package
+#                 output="[]"
+#                 for pkg in $(echo $affected | jq -r '.[]'); do
+#                     echo "Publishing $pkg"
+#                     set +e
+#                     npm publish -w "$pkg" --access public --registry https://registry.npmjs.org
+#                     result=$?
+#                     set -e
+#                     if [ $result -eq 0 ]; then
+#                       output=$(echo "$output" | jq -c ". += [{\"package\": \"$pkg\", \"ok\": true}]")
+#                     else
+#                       output=$(echo "$output" | jq -c ". += [{\"package\": \"$pkg\", \"ok\": false}]")
+#                     fi
+#                 done
 
-                echo "output: $output"
-                echo "output=$output" >> $GITHUB_OUTPUT
+#                 echo "output: $output"
+#                 echo "output=$output" >> $GITHUB_OUTPUT
 
-                failed=$(echo "$output" | jq '[.[] | select(.ok==false)] | length')
-                if [ "$failed" -gt 0 ]; then
-                    echo "Some packages failed to publish to GitHub Packages"
-                    exit 1
-                fi
+#                 failed=$(echo "$output" | jq '[.[] | select(.ok==false)] | length')
+#                 if [ "$failed" -gt 0 ]; then
+#                     echo "Some packages failed to publish to GitHub Packages"
+#                     exit 1
+#                 fi
 
-            - name: publish to gh
-              id: publish_gh
-              if: steps.publish_npm.outcome != 'skipped' # run this step if the previous step was not skipped due to error in previous step
-              run: |
-                # make all packages non-private - this just means we can publish them, not that they're public!
-                npm pkg -ws delete private
-                # for each affected package
-                output="[]"
-                for pkg in $(echo $affected | jq -r '.[]'); do
-                    echo "Publishing $pkg"
-                    # restricted access for private packages on gh (only accessible to the org)
-                    set +e
-                    npm publish -w "$pkg" --access restricted --registry https://npm.pkg.github.com
-                    result=$?
-                    set -e
-                    if [ $result -eq 0 ]; then
-                      output=$(echo "$output" | jq -c ". += [{\"package\": \"$pkg\", \"ok\": true}]")
-                    else
-                      output=$(echo "$output" | jq -c ". += [{\"package\": \"$pkg\", \"ok\": false}]")
-                    fi
-                done
+#             - name: publish to gh
+#               id: publish_gh
+#               if: steps.publish_npm.outcome != 'skipped' # run this step if the previous step was not skipped due to error in previous step
+#               run: |
+#                 # make all packages non-private - this just means we can publish them, not that they're public!
+#                 npm pkg -ws delete private
+#                 # for each affected package
+#                 output="[]"
+#                 for pkg in $(echo $affected | jq -r '.[]'); do
+#                     echo "Publishing $pkg"
+#                     # restricted access for private packages on gh (only accessible to the org)
+#                     set +e
+#                     npm publish -w "$pkg" --access restricted --registry https://npm.pkg.github.com
+#                     result=$?
+#                     set -e
+#                     if [ $result -eq 0 ]; then
+#                       output=$(echo "$output" | jq -c ". += [{\"package\": \"$pkg\", \"ok\": true}]")
+#                     else
+#                       output=$(echo "$output" | jq -c ". += [{\"package\": \"$pkg\", \"ok\": false}]")
+#                     fi
+#                 done
 
-                echo "output: $output"
-                echo "output=$output" >> $GITHUB_OUTPUT
+#                 echo "output: $output"
+#                 echo "output=$output" >> $GITHUB_OUTPUT
                 
-                failed=$(echo "$output" | jq '[.[] | select(.ok==false)] | length')
-                if [ "$failed" -gt 0 ]; then
-                    echo "Some packages failed to publish to GitHub Packages"
-                    exit 1
-                fi
+#                 failed=$(echo "$output" | jq '[.[] | select(.ok==false)] | length')
+#                 if [ "$failed" -gt 0 ]; then
+#                     echo "Some packages failed to publish to GitHub Packages"
+#                     exit 1
+#                 fi
 
-            - name: print output
-              if: always()
-              run: |
-                echo "npm output: ${{ steps.publish_npm.outputs.output }}"
-                echo "gh output: ${{ steps.publish_gh.outputs.output }}"
-                npm_nok=$(echo '${{ steps.publish_npm.outputs.output }}' | jq '[.[] | select(.ok==false)]')
-                npm_ok=$(echo '${{ steps.publish_npm.outputs.output }}' | jq '[.[] | select(.ok==true)]')
-                gh_nok=$(echo '${{ steps.publish_gh.outputs.output }}' | jq '[.[] | select(.ok==false)]')
-                gh_ok=$(echo '${{ steps.publish_gh.outputs.output }}' | jq '[.[] | select(.ok==true)]')
+#             - name: print output
+#               if: always()
+#               run: |
+#                 echo "npm output: ${{ steps.publish_npm.outputs.output }}"
+#                 echo "gh output: ${{ steps.publish_gh.outputs.output }}"
+#                 npm_nok=$(echo '${{ steps.publish_npm.outputs.output }}' | jq '[.[] | select(.ok==false)]')
+#                 npm_ok=$(echo '${{ steps.publish_npm.outputs.output }}' | jq '[.[] | select(.ok==true)]')
+#                 gh_nok=$(echo '${{ steps.publish_gh.outputs.output }}' | jq '[.[] | select(.ok==false)]')
+#                 gh_ok=$(echo '${{ steps.publish_gh.outputs.output }}' | jq '[.[] | select(.ok==true)]')
 
-                npm_success=$(echo "$npm_ok" | jq -r '.[].package')
-                gh_success=$(echo "$gh_ok" | jq -r '.[].package')
-                npm_failure=$(echo "$npm_nok" | jq -r '.[].package')
-                gh_failure=$(echo "$gh_nok" | jq -r '.[].package')
+#                 npm_success=$(echo "$npm_ok" | jq -r '.[].package')
+#                 gh_success=$(echo "$gh_ok" | jq -r '.[].package')
+#                 npm_failure=$(echo "$npm_nok" | jq -r '.[].package')
+#                 gh_failure=$(echo "$gh_nok" | jq -r '.[].package')
 
-                if [ -n "$npm_success" ]; then
-                  echo "Successfully published to npm:"
-                  echo "$npm_success"
-                  echo ""
-                fi
+#                 if [ -n "$npm_success" ]; then
+#                   echo "Successfully published to npm:"
+#                   echo "$npm_success"
+#                   echo ""
+#                 fi
 
-                if [ -n "$gh_success" ]; then
-                  echo "Successfully published to GitHub Packages:"
-                  echo "$gh_success"
-                  echo ""
-                fi
+#                 if [ -n "$gh_success" ]; then
+#                   echo "Successfully published to GitHub Packages:"
+#                   echo "$gh_success"
+#                   echo ""
+#                 fi
                 
-                if [ -n "$npm_failure" ]; then
-                  echo "Failed to publish to npm:"
-                  echo "$npm_failure"
-                  echo ""
-                fi
+#                 if [ -n "$npm_failure" ]; then
+#                   echo "Failed to publish to npm:"
+#                   echo "$npm_failure"
+#                   echo ""
+#                 fi
 
-                if [ -n "$gh_failure" ]; then
-                  echo "Failed to publish to GitHub Packages:"
-                  echo "$gh_failure"
-                  echo ""
-                fi
+#                 if [ -n "$gh_failure" ]; then
+#                   echo "Failed to publish to GitHub Packages:"
+#                   echo "$gh_failure"
+#                   echo ""
+#                 fi
