z16

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -86,13 +86,15 @@ jobs:
             - name: build+bundle
               run: |
                 echo "Building and bundling affected packages"
-                npx nx run-many --target=bundle --projects=$(echo $affected | jq -r 'keys | join(",")')
+                npx nx run-many --target=build,build:cjs,bundle --projects=$(echo $affected | jq -r 'keys | join(",")')
 
             - name: push
               env:
                 GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
               run: |
-                git push --follow-tags || true # allow the push to fail if there are no changes to push
+                # allow the push to fail if there are no changes to push
+                git push || true
+                git push --tags || true
 
             - name: publish
               id: publish
